name: Build Android APK

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'master'
          cache: true

      - name: Build Android ARM64 APK
        run: |
          git config --global core.longpaths true
          flutter pub get
          flutter build apk -t lib/src/main.dart --release --target-platform android-arm64

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JHenTai-coexist-arm64-v8a-release
          path: build/app/outputs/**/*.apk
